global:
  scrape_interval:     5s

scrape_configs:
  - job_name: 'simple-e2e-app'
    metrics_path: /scrape
    static_configs:
      - targets: ['host.docker.internal:8001', "this.doesnt.exist.com:12345"]
