global:
  scrape_interval:     1s

scrape_configs:
  - job_name: 'dimensional-app'
    metrics_path: /scrape
    static_configs:
      - targets: ['host.docker.internal:8002']
  - job_name: 'also-dimensional-app'
    metrics_path: /scrape
    static_configs:
      - targets: ['host.docker.internal:8002']
