global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']
    relabel_configs:
      # use the `Name` tag instead of a random IP
      - action: replace
        source_labels: [ "__meta_ec2_tag_Name"]
        target_label: "instance"

  - job_name: 'spring-boot'
    metrics_path: /actuator/prometheus
    ec2_sd_configs:
      - region: us-east-1
        port: 8080
        filters:
          - name: "tag:Workload"
            values: ['spring-boot']
    relabel_configs:
      # use the `Name` tag instead of a random IP
      - action: replace
        source_labels: [ "__meta_ec2_tag_Name"]
        target_label: "instance"

  - job_name: 'node-exporter'
    metrics_path: /metrics
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: "tag:Workload"
            values: ['*']
    relabel_configs:
      # use the `Name` tag instead of a random IP
      - action: replace
        source_labels: [ "__meta_ec2_tag_Name"]
        target_label: "instance"
      - action: replace
        source_labels: [ "__meta_ec2_tag_Workload"]
        target_label: "workload"

