global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'binders-app'
    metrics_path: /scrape
    static_configs:
      - targets: ['host.docker.internal:8008']
    relabel_configs:
      - action: replace
        replacement: binders-app
        target_label: application
