client:
  url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring
    pipeline_stages:
      - json:
          expressions:
            level: level
      - labels:
          level:
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/log/spring/*.log
          job: spring